### ISSUE TITLE
Null Reference Error

### ISSUE THREAD

**Issue by myusernamedm** [LazZiya/ExpressLocalization#34]
Hi Laz, I hope you are keeping safe and well.

I'm struggling with a null reference error for localized values when I scaffold in the ForgotPassword page in .Net 5.0. I have been trying to follow implementation from the ExpressLocalization .Net Core example project, and have reviewed the prior issues here on GitHub, but am still having the same problem. The confusing thing is that it has not happened on other pages I have scaffolded in.

**Exception:**

```
An unhandled exception occurred while processing the request.
ArgumentNullException: Value cannot be null. (Parameter 'name')
Microsoft.AspNetCore.Mvc.Localization.HtmlLocalizer.get_Item(string name, object[] arguments)

Stack Query Cookies Headers Routing
ArgumentNullException: Value cannot be null. (Parameter 'name')
Microsoft.AspNetCore.Mvc.Localization.HtmlLocalizer.get_Item(string name, object[] arguments)
LazZiya.ExpressLocalization.SharedCultureLocalizer.GetLocalizedString(string key, object[] args)
LazZiya.ExpressLocalization.SharedCultureLocalizer.get_Item(string key)
AspNetCore.Areas_Identity_Pages_Account_ForgotPassword.ExecuteAsync() in ForgotPassword.cshtml
+
    ViewData["Title"] = _loc[Model.PageTabTitle];
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, 
```

When I replace `ViewData["Title"] = _loc[Model.PageTabTitle];` with `ViewData["Title"] = "Test";` in my .cshtml file, the error simply appears for the next localized value down the page. Plus using `_loc[Model.PageTabTitle]` works fine on the other pages, so its not an issue with my string referencing.

**.cshtml**

```
@page
@model ForgotPasswordModel
@using LazZiya.ExpressLocalization
@using System.Globalization
@inject ISharedCultureLocalizer _loc
@{
    ViewData["Title"] = _loc[Model.PageTabTitle];
    var culture = System.Globalization.CultureInfo.CurrentCulture.Name;
}
```

**Link to ForgotPassword page from Login.cshtml:**

`<a class="link-style" asp-page="./ForgotPassword" asp-route-culture="@CultureInfo.CurrentCulture.Name" id="LoginForgotPasswordLink">@_loc[Model.ForgotPassword]</a>`

**Model/Controller .cshtml.cs file**

I have the parameter specified in my model and referenced in the OnPostAsync method:

`public string PageTabTitle { get; set; }`
        
and

`PageTabTitle = _locSourceForgotPasswordPageNameReferenceLibrary.GetLocSourcePageTabTitleNameReferenceForForgotPasswordPage();  `    

There are no build errors and the URL appears to be correct:

`https://localhost:44305/en/Identity/Account/ForgotPassword`

I have compared to my other scaffolded pages which are working fine, I cant figure out why this one is different. Any ideas would be appreciated?

**Comment by LazZiya** [comment]
Hi @myusernamedm , Thanks I'm good, hope you are also fine :)

Did you tried with debugging mode? maybe it can show which line is throwing the exception or you can debug the binding params.

btw, do you have `[BindProperty]` attribute for `PageTabTitle`?

````cs
[BindProperty]
public string PageTabTitle { get; set; }
````

**Comment by myusernamedm** [comment]
Thanks for the reply Laz, I did not have BindProperty for that specific property, but I have added it and there is no change.

Yes I tried with the debugger, the below is showing a localisation error I believe


```
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2 GET https://localhost:44305/en/Identity/Account/ForgotPassword - -
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint '/Account/ForgotPassword'
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Information: Route matched with {page = "/Account/ForgotPassword", area = "Identity", action = "", controller = ""}. Executing page /Account/ForgotPassword
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Information: Executing an implicit handler method - ModelState is Valid
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Information: Executed an implicit handler method, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.

Exception thrown: 'System.ArgumentNullException' in Microsoft.AspNetCore.Mvc.Localization.dll

Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Information: Executed page /Account/ForgotPassword in 228.2108ms
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint '/Account/ForgotPassword'
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.8\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.8\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.8\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.8\System.IO.MemoryMappedFiles.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.ArgumentNullException: Value cannot be null. (Parameter 'name')
   at Microsoft.AspNetCore.Mvc.Localization.HtmlLocalizer.get_Item(String name, Object[] arguments)
   at LazZiya.ExpressLocalization.SharedCultureLocalizer.GetLocalizedString(String key, Object[] args)
   at AspNetCore.Areas_Identity_Pages_Account_ForgotPassword.ExecuteAsync() in C:\Users\diarm\Source\Repos\GatheringForGood_Main\GatheringForGood\Areas\Identity\Pages\Account\ForgotPassword.cshtml:line 7
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Microsoft.EntityFrameworkCore.Model.Validation: Warning: Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
Microsoft.EntityFrameworkCore.Infrastructure: Information: Entity Framework Core 5.0.8 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: SensitiveDataLoggingEnabled 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Users\diarm\Source\Repos\GatheringForGood_Main\GatheringForGood\bin\Debug\net5.0\runtimes\win\lib\netcoreapp3.1\Microsoft.Data.SqlClient.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.8\System.Threading.Timer.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.8\System.Resources.ResourceManager.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Users\diarm\Source\Repos\GatheringForGood_Main\GatheringForGood\bin\Debug\net5.0\System.Configuration.ConfigurationManager.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.8\System.Xml.ReaderWriter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.8\System.Net.WebClient.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.8\System.Text.Encoding.CodePages.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.8\System.Buffers.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.8\System.Diagnostics.Process.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x3734 has exited with code 0 (0x0).
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (111ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (128ms) [Parameters=[], CommandType='Text', CommandTimeout='30']

IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (54ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (56ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (82ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished HTTP/2 GET https://localhost:44305/en/Identity/Account/ForgotPassword - - - 500 - text/html;+charset=utf-8 4354.2028ms
```

**Comment by LazZiya** [comment]
Hi @myusernamedm ,

I’m not able to offer a solution now due to some health issues :( may be after two weeks I will be able to help.

**Comment by myusernamedm** [comment]
Hi Laz, that is no problem at all, take care of your health, it is much more important. I hope you recover safe and well.
